services:
  time:
    build: .
    container_name: time
    ports: 
      - $PORT:$PORT
    environment:
      - MEDIAURL
      - PORT
    image: lucas42/lucos_time
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:${PORT}/_info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    network_mode: host