services:
  time:
    build: .
    container_name: lucos_time
    ports: 
      - $PORT:$PORT
    environment:
      - MEDIAURL
      - PORT
      - KEY_LUCOS_EOLAS
      - EOLAS_URL
      - SCHEDULE_TRACKER_ENDPOINT
    image: lucas42/lucos_time:${VERSION:-latest}
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:${PORT}/_info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    network_mode: host